# Generated by Django 4.2.1 on 2023-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
