# Generated by Django 4.2.1 on 2023-05-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customersadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersadress',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersadress',
            name='street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomersAddhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addhar_name', models.CharField(blank=True, max_length=15, null=True)),
                ('adahar_number', models.IntegerField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
        ),
    ]
